
project:
  type: website

website:
  title: "ISSS624GAA"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands_on_Ex1/Hands_on_Ex1.qmd
          - text: Hands-on Exercise 2
            href: Hands_on_Ex2/Hands_on_Ex2.qmd
          - text: Hands_on Exercise 3
            href: Hands_on_Ex3/Hands_on_Ex3.qmd
          - text: Hands_on Exercise 4
            href: Hands_on_Ex4/Hands_on_Ex4.qmd
      - text: Inclass Exercises
        menu: 
          - text: Inclass Exercise 1
            href: Inclass_Ex1/Inclass_Ex1.qmd
          - text: Inclass Exercise 2
            href: Inclass_Ex2/Inclass_Ex2.qmd 
          - text: Inclass Exercise 3
            href: Inclass_Ex3/Inclass_Ex3.qmd 
          - text: Inclass Exercise 4
            href: Inclass_Ex4/Inclass_Ex4.qmd
            
      - text: Take Home Exercises
        menu: 
          - text: Take Home Exercise 1
            href: Take_home_Ex1/Take_home_Ex1.qmd
      - text: R4DSA Exercises
        menu: 
          - text: R4DSA Exercise 1
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: spacelab
    fontsize: 1.1em
    linestretch: 1.7
    

editor: visual

